# Generated by Django 3.1 on 2022-11-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20221123_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('colour', 'colour'), ('size', 'size')], max_length=100),
        ),
    ]
