# Generated by Django 3.1 on 2022-11-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20221115_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
