# Generated by Django 3.1 on 2022-12-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_address_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
